import { NextRequest, NextResponse } from 'next/server';
import { requireAuth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { getTodayInTaiwan } from '@/lib/dateUtils';

// 使用 Gemini 生成每日主題
async function generateDailyTopicWithGemini(): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;
  
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY is not set');
  }

  const genAI = new GoogleGenerativeAI(apiKey);
  const model = genAI.getGenerativeModel({ model: 'gemini-pro' });

  const prompt = `請生成一個適合交友平台的每日話題，要求：
1. 話題應該有趣、輕鬆，能引發討論
2. 話題應該適合年輕族群（20-30歲）
3. 話題應該能幫助人們了解彼此
4. 只回傳話題本身，不要有其他說明文字
5. 話題長度在 10-30 字之間
6. 使用繁體中文

範例：
- 如果今天不用工作，你最想做什麼？
- 你覺得什麼樣的約會最浪漫？
- 你最近看過最推薦的電影或劇集是什麼？

請生成今日話題：`;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text().trim();
    
    // 清理回傳的文字（移除可能的引號或額外說明）
    let topic = text.replace(/^["']|["']$/g, '').trim();
    
    // 如果回傳太長，取第一句
    if (topic.length > 50) {
      topic = topic.split(/[。！？\n]/)[0].trim();
    }
    
    return topic || '今天想聊聊什麼？';
  } catch (error) {
    console.error('Gemini API error:', error);
    // 如果 Gemini 失敗，回傳預設話題
    const fallbackTopics = [
      '今天想聊聊什麼？',
      '你最近有什麼有趣的事情想分享？',
      '如果今天不用工作，你最想做什麼？',
      '你覺得什麼樣的約會最浪漫？',
      '你最近看過最推薦的電影或劇集是什麼？',
    ];
    const randomIndex = Math.floor(Math.random() * fallbackTopics.length);
    return fallbackTopics[randomIndex];
  }
}

// GET: 取得今日主題
export async function GET(request: NextRequest) {
  const authResult = await requireAuth(request);
  
  if (authResult instanceof Response) {
    return authResult;
  }

  try {
    // 取得台灣時間的今天日期
    const { start: today, end: todayEnd } = getTodayInTaiwan();

    // 查詢今日主題
    const topic = await prisma.dailyTopic.findFirst({
      where: {
        date: {
          gte: today,
          lte: todayEnd,
        },
      },
      include: {
        _count: {
          select: {
            posts: true,
          },
        },
      },
    });

    // 如果今天沒有主題，自動生成一個
    if (!topic) {
      try {
        // 使用 Gemini 生成主題
        const generatedTitle = await generateDailyTopicWithGemini();
        
        // 建立新主題
        const newTopic = await prisma.dailyTopic.create({
          data: {
            date: today,
            title: generatedTitle,
          },
          include: {
            _count: {
              select: {
                posts: true,
              },
            },
          },
        });

        return NextResponse.json({
          topic: {
            id: newTopic.id,
            date: newTopic.date.toISOString(),
            title: newTopic.title,
            postCount: newTopic._count.posts,
            createdAt: newTopic.createdAt.toISOString(),
          },
          autoGenerated: true,
        });
      } catch (error) {
        console.error('Auto-generate topic error:', error);
        // 如果自動生成失敗，回傳 null
        return NextResponse.json({
          topic: null,
          message: '今日尚無主題',
        });
      }
    }

    return NextResponse.json({
      topic: {
        id: topic.id,
        date: topic.date.toISOString(),
        title: topic.title,
        postCount: topic._count.posts,
        createdAt: topic.createdAt.toISOString(),
      },
    });
  } catch (error) {
    console.error('Get daily topic error:', error);
    return NextResponse.json(
      { error: 'Failed to get daily topic' },
      { status: 500 }
    );
  }
}

// POST: 建立每日主題（管理員功能，暫時開放給所有登入用戶）
export async function POST(request: NextRequest) {
  const authResult = await requireAuth(request);
  
  if (authResult instanceof Response) {
    return authResult;
  }

  try {
    const { title } = await request.json();

    if (!title || !title.trim()) {
      return NextResponse.json(
        { error: 'Title is required' },
        { status: 400 }
      );
    }

    // 取得台灣時間的今天日期
    const { start: today, end: todayEnd } = getTodayInTaiwan();

    // 檢查今天是否已有主題
    const existingTopic = await prisma.dailyTopic.findFirst({
      where: {
        date: {
          gte: today,
          lte: todayEnd,
        },
      },
    });

    if (existingTopic) {
      // 更新現有主題
      const updated = await prisma.dailyTopic.update({
        where: { id: existingTopic.id },
        data: { title: title.trim() },
      });

      return NextResponse.json({
        topic: {
          id: updated.id,
          date: updated.date.toISOString(),
          title: updated.title,
          createdAt: updated.createdAt.toISOString(),
        },
      });
    }

    // 建立新主題
    const topic = await prisma.dailyTopic.create({
      data: {
        date: today,
        title: title.trim(),
      },
    });

    return NextResponse.json({
      topic: {
        id: topic.id,
        date: topic.date.toISOString(),
        title: topic.title,
        createdAt: topic.createdAt.toISOString(),
      },
    }, { status: 201 });
  } catch (error: any) {
    console.error('Create daily topic error:', error);
    
    // 處理唯一約束錯誤（同一天不能有兩個主題）
    if (error.code === 'P2002') {
      return NextResponse.json(
        { error: '今日主題已存在' },
        { status: 409 }
      );
    }

    return NextResponse.json(
      { error: error.message || 'Failed to create daily topic' },
      { status: 500 }
    );
  }
}
